# Generated by Django 3.0.4 on 2020-04-02 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='', max_length=50)),
                ('note', models.TextField(default='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('owner_username', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
